#!/usr/bin/env bash

#export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

# if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
#     curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
# else
#     	php $OPENSHIFT_DATA_DIR\composer.phar self-update
# fi

unset GIT_DIR

echo "running deploy scripts"
# ln -sf $OPENSHIFT_DATA_DIR\assets $OPENSHIFT_REPO_DIR/php/
# ln -sf $OPENSHIFT_DATA_DIR\cache $OPENSHIFT_REPO_DIR/php/
#link assets and cache folders to the persistent data directories
# ln -sf $OPENSHIFT_DATA_DIR\api/assets $OPENSHIFT_REPO_DIR/api/
# ln -sf $OPENSHIFT_DATA_DIR\api/cache $OPENSHIFT_REPO_DIR/api/

# php $OPENSHIFT_REPO_DIR\php/framework/cli-script.php dev/build flush=1
php "${OPENSHIFT_REPO_DIR}\php/framework/cli-script.php" jsonservice/Indego/sync

php "${OPENSHIFT_REPO_DIR}\php/framework/cli-script.php" jsonservice/Trip/count start=01-01-2015

OLD_HOME="${HOME}"
pushd "${OPENSHIFT_REPO_DIR}"
    HOME=`pwd`
    npm config set prefix=~/npm
    export PATH="${PATH}:~/npm/bin"
    npm cache clean
    npm install -g bower
    bower install
popd
HOME="${OLD_HOME}"
